### ISSUE TITLE
--boot_adb_kernel Causing update to fail

### ISSUE THREAD

**Issue by ivybowman** [bishopdynamics/superbird-tool#4]
I just discovered something that's an issue, booting the ADB kernel from your tool changes the cmd line very slightly so (from a fresh image) it errors on trying to pull the active boot slot. Pictured below is the output of /proc/cmdline with your tool(top) and bulkcmd (bottom)
![image](https://user-images.githubusercontent.com/18595973/199629796-26831536-7f5c-41e4-98cb-509bf1449575.png)

**Comment by bishopdynamics** [comment]
@ivybowman  I think you just figured out the problem for both issues! I was accidentally encoding the env data in utf-8, but the device wants ascii. It only appeared to work before because the lower 7 bits of utf-8 are the same as ascii, but that weird line termination in your screenshot gave it away!
